include: package:lints/recommended.yaml

analyzer:
  errors:
    invalid_annotation_target: ignore

linter:
  rules:
    avoid_function_literals_in_foreach_calls: false
    prefer_single_quotes: false